development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:a74d840fb33c81394bc74b856adcce51@scat.redistogo.com:10958/
  channel_prefix: MessageMe_production
